x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - TZ=Asia/Tokyo
  ports:
    - "7860:7860"
  volumes:
    - /sd_data/framepack:/app/framepack/data
    - /sd_data/models:/app/framepack/hf_download
    - /sd_output/framepack:/app/framepack/outputs
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  restart: unless-stopped

services:
  endframe:
    <<: *common
    command: ["python endframe_ichi.py", "--server", "0.0.0.0", "--port", "7860","--lang", "ja"]

  oneframe:
    <<: *common
    command: ["python oneframe_ichi.py", "--server", "0.0.0.0", "--port", "7860","--lang", "ja"]
  oneframe_f1:
    <<: *common
    command: ["python oneframe_ichi_f1.py", "--server", "0.0.0.0", "--port", "7860","--lang", "ja"]